all: clean

prep:
	mkdir -p mdb
	mkdir -p outputs
	mkdir -p reports

clean:
	rm -rf __tmp*
	rm -rf .tmp_*
	rm -rf command.log
	rm -rf icc_output.txt
	rm -rf net.acts
	rm -rf *map.*
	rm -rf outputs
	rm -rf reports
	rm -rf snapshot
	rm -rf TMP
	rm -rf mdb
