*** Milkyway Database Commands 
MILKYWAY_CELL_VIEW : adder_top
MILKYWAY_DATABASE : ../layout/mdb/adder_top_chip_finish
MILKYWAY_REF_LIB_MODE : NONE
*PROCESS_CORNER : 

*** Shared Database Commands
BLOCK : adder_top
CASE_SENSITIVE:           YES
HIERARCHICAL_SEPARATOR : /

*** Extraction Commands
COUPLE_TO_GROUND : YES
EXTRACTION : RC 
IGNORE_CAPACITANCE : ALL
REDUCTION : YES 
REDUCTION_MAX_DELAY_ERROR : 1.0e-12

MAPPING_FILE: /home/user/PDK/BE/StarRCXT/StarRCXT_HL18G_LPE_S3.7_a/StarRCXT_HL18G_STD_LPE_S3.7_a/StarRCXT_HL18G_M15_PnRDB_S3.7_a/HL18G_5LM.mapping.m2s
TCAD_GRD_FILE:/home/user/PDK/BE/StarRCXT/StarRCXT_HL18G_LPE_S3.7_a/StarRCXT_HL18G_STD_LPE_S3.7_a/StarRCXT_HL18G_M15_PnRDB_S3.7_a/HL18G_L28_STD_5LM_worstRC.nxtgrd


*** Processing Commands
NETS : *
POWER_EXTRACT : NO
*REMOVE_NO_CONNECT_NETS : YES 
SHORT_PINS : YES 
POWER_NETS:                VSS VDD
NETLIST_SUBCKT: NO
 
NETLIST_FILE:             adder_top_worstRC.SPEF
NETLIST_FORMAT : SPEF 
NETLIST_NODE_SECTION : YES 
*NETLIST_ONLY_TEXTED_NETS: YES
** Below is for deviding netlist file to ideal instance and parasitic nets files
*NETLIST_IDEAL_SPICE_FILE : pad_TOP_worstRC.sp.c
*NETLIST_IDEAL_SPICE_TYPE : SCHEMATIC
*NETLIST_IDEAL_SPICE_HIER : YES
*NETLIST_INSTANCE_SECTION : NO
