set_attribute -type boolean [get_pins pad68/PAD] is_pad true
set_attribute -type boolean [get_pins pad67/PAD] is_pad true
set_attribute -type boolean [get_pins pad66/PAD] is_pad true
set_attribute -type boolean [get_pins pad65/PAD] is_pad true
set_attribute -type boolean [get_pins pad64/PAD] is_pad true
set_attribute -type boolean [get_pins pad63/PAD] is_pad true
set_attribute -type boolean [get_pins pad62/PAD] is_pad true
set_attribute -type boolean [get_pins pad57/PAD] is_pad true
set_attribute -type boolean [get_pins pad56/PAD] is_pad true
set_attribute -type boolean [get_pins pad55/PAD] is_pad true
set_attribute -type boolean [get_pins pad54/PAD] is_pad true
set_attribute -type boolean [get_pins pad53/PAD] is_pad true
set_attribute -type boolean [get_pins pad52/PAD] is_pad true
set_attribute -type boolean [get_pins pad51/PAD] is_pad true
set_attribute -type boolean [get_pins pad50/PAD] is_pad true
set_attribute -type boolean [get_pins pad49/PAD] is_pad true
set_attribute -type boolean [get_pins pad48/PAD] is_pad true
set_attribute -type boolean [get_pins pad47/PAD] is_pad true
set_attribute -type boolean [get_pins pad46/PAD] is_pad true
set_attribute -type boolean [get_pins pad45/PAD] is_pad true
set_attribute -type boolean [get_pins pad40/PAD] is_pad true
set_attribute -type boolean [get_pins pad39/PAD] is_pad true
set_attribute -type boolean [get_pins pad38/PAD] is_pad true
set_attribute -type boolean [get_pins pad37/PAD] is_pad true
set_attribute -type boolean [get_pins pad36/PAD] is_pad true
set_attribute -type boolean [get_pins pad35/PAD] is_pad true
set_attribute -type boolean [get_pins pad34/PAD] is_pad true
set_attribute -type boolean [get_pins pad33/PAD] is_pad true
set_attribute -type boolean [get_pins pad32/PAD] is_pad true
set_attribute -type boolean [get_pins pad31/PAD] is_pad true
set_attribute -type boolean [get_pins pad30/PAD] is_pad true
set_attribute -type boolean [get_pins pad29/PAD] is_pad true
set_attribute -type boolean [get_pins pad28/PAD] is_pad true
set_attribute -type boolean [get_pins pad23/PAD] is_pad true
set_attribute -type boolean [get_pins pad22/PAD] is_pad true
set_attribute -type boolean [get_pins pad21/PAD] is_pad true
set_attribute -type boolean [get_pins pad20/PAD] is_pad true
set_attribute -type boolean [get_pins pad19/PAD] is_pad true
set_attribute -type boolean [get_pins pad18/PAD] is_pad true
set_attribute -type boolean [get_pins pad17/PAD] is_pad true
set_attribute -type boolean [get_pins pad16/PAD] is_pad true
set_attribute -type boolean [get_pins pad15/PAD] is_pad true
set_attribute -type boolean [get_pins pad14/PAD] is_pad true
set_attribute -type boolean [get_pins pad13/PAD] is_pad true
set_attribute -type boolean [get_pins pad12/PAD] is_pad true
set_attribute -type boolean [get_pins pad11/PAD] is_pad true
set_attribute -type boolean [get_pins pad6/PAD] is_pad true
set_attribute -type boolean [get_pins pad5/PAD] is_pad true
set_attribute -type boolean [get_pins pad4/PAD] is_pad true
set_attribute -type boolean [get_pins pad3/PAD] is_pad true
set_attribute -type boolean [get_pins pad2/PAD] is_pad true
set_attribute -type boolean [get_pins pad1/PAD] is_pad true
